### ISSUE TITLE
After recent changes, tweets do not appear in Firefox 68.0.2 (64-bit) because of CORS failure

### ISSUE THREAD

**Issue by jmcastagnetto** [nsgrantham/tidytuesdayrocks#12]
Tried this on Linux and also on Windows. The problem seems to be documented in https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

In the Web Developer console in the error shows as:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://syndication.twitter.com/settings. (Reason: CORS request did not succeed).
```

Also, I see this error:

```
Loading failed for the <script> with source “https://platform.twitter.com/js/tweet.73b7ab8a56ad3263cad8d36ba66467fc.js”.
```

In Chrome (running on Linux or Windows), everything seems to work.

As a reference, here is what it looks like in Firefox:

![screenshot-nsgrantham shinyapps io-2019 08 29-10_48_31](https://user-images.githubusercontent.com/364668/63955706-c7346080-ca4a-11e9-852f-8f5bd05c4c98.png)

And here is with the Developer Console open:

![2019-08-29 10_52_56-Mozilla Firefox](https://user-images.githubusercontent.com/364668/63956030-4fb30100-ca4b-11e9-9434-a17aea2374c3.png)

**Comment by nsgrantham** [comment]
Thanks @jmcastagnetto! I'll see if I can reproduce the problem myself and fix it this weekend (hopefully)

**Comment by nsgrantham** [comment]
Well, it seems there error does not appear with Firefox 69.0 on my Ubuntu machine. @jmcastagnetto, if you're able to upgrade, can you confirm that this fixes the error?

If not, the resource you linked about the CORS error suggests it may come from a browser plugin, like an ad blocker or privacy protector. I can't imagine why that might be the case — tidytuesday.rocks is very simple and doesn't do anything funky, although I suppose it could be triggered when the JavaScript "embeds" the tweets.

**Comment by jmcastagnetto** [comment]
@nsgrantham, you are correct Neal -- it was the DuckDuck Go extension I had installed recently. Used their feedback interface to tell them about the issue. Meanwhile, have whitelisted tidytuesday.rocks and all is well in web-land :-)

Off topic: used your very nice ggdark themes and my son (looking at what I was doing) thinks they are "awesome" and should be my default, so you got 2 new fans.

**Comment by nsgrantham** [comment]
Glad to hear it! I do wonder what tidytuesday.rocks is doing that the extension doesn't like, but I probably won't dig into it any further unless it becomes a bigger problem.

You and your son have great taste, welcome to the dark side 😎
